language: php

php:
    - '7.1'
    - '7.2'

jobs:
  include:
    # - os: linux
    #   dist: xenial
    - os: windows
      language: sh
      before_install:
          - choco install php --version=7.2.2
          - export PATH=/c/tools/php73:$PATH
          - choco install composer --ia /DEV="C:\tools"
          - export PATH=/c/tools/:$PATH
        
  allow_failures:
    - os: windows

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install

before_script:
  - composer validate --no-check-all --strict
  - composer update $PREFER_LOWEST  

script:
  - 'composer test'



