<?php


namespace Morebec\YDB\YQL;

use Morebec\YDB\YQL\Parser\YQLParser;
use Morebec\YDB\YQL\Query\ExpressionQuery;

/**
 * Class Query
 */
class Query extends ExpressionQuery
{
    /**
     * @var string
     */
    private $query;

    private $parsed = false;

    public function __construct(string $query)
    {
        $this->query = $query;
        // parent::__construct(null, null, null); // Skip parent
    }

    public function parse(): void
    {
        $result = YQLParser::parse($this->query);
        $this->expression = $result->expressionNode;
        $this->cardinality = $result->cardinality;
        $this->collectionName = $result->collectionName;
    }

    public function getCardinality(): Cardinality
    {
        $this->ensureParsed();
        return parent::getCardinality(); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getCollectionName(): string
    {
        $this->ensureParsed();
        return $this->collectionName;
    }

    public function getExpression(): ExpressionNode
    {
        $this->ensureParsed();
        return parent::getExpression(); // TODO: Change the autogenerated stub
    }

    private function ensureParsed(): void
    {
        if (!$this->parsed) {
            $this->parse();
        }
    }
}